chore: fix workflow always fail

diff --git a/.github/workflows/code-analysis.yml b/.github/workflows/code-analysis.yml
--- a/.github/workflows/code-analysis.yml
+++ b/.github/workflows/code-analysis.yml
@@ -18,8 +18,8 @@ jobs:
           npm ci && \
           npm run format:check && \
           echo -e "\033[32m FORMAT CHECK PASSED \033[0m" || \
-          echo -e "\033[31m FORMAT CHECK FAILED \033[0m" && \
-          exit 1
+          (echo -e "\033[31m FORMAT CHECK FAILED \033[0m" && exit 1)
+
   lint:
     name: ESLint check
     runs-on: ubuntu-latest
@@ -31,8 +31,7 @@ jobs:
           npm ci && \
           npm run lint && \
           echo -e "\033[32m LINT PASSED \033[0m" || \
-          echo -e "\033[31m LINT FAILED \033[0m" && \
-          exit 1
+          (echo -e "\033[31m LINT FAILED \033[0m" && exit 1)
 
   windows_test:
     needs: [format, lint]
@@ -57,8 +56,7 @@ jobs:
           npm ci && \
           npm run test && \
           echo -e "\033[32m WINDOWS PASSED \033[0m" || \
-          echo -e "\033[31m WINDOWS FAILED \033[0m" && \
-          exit 1
+          (echo -e "\033[31m WINDOWS FAILED \033[0m" && exit 1)
 
   darwin_test:
     needs: [format, lint]
@@ -72,5 +70,4 @@ jobs:
           npm ci && \
           npm run test && \
           echo -e "\033[32m WINDOWS PASSED \033[0m" || \
-          echo -e "\033[31m WINDOWS FAILED \033[0m" && \
-          exit 1
+          (echo -e "\033[31m WINDOWS FAILED \033[0m" && exit 1)
