chore: fix workflow always pass

diff --git a/.github/workflows/code-analysis.yml b/.github/workflows/code-analysis.yml
--- a/.github/workflows/code-analysis.yml
+++ b/.github/workflows/code-analysis.yml
@@ -18,7 +18,8 @@ jobs:
           npm ci && \
           npm run format:check && \
           echo -e "\033[32m FORMAT CHECK PASSED \033[0m" || \
-          echo -e "\033[31m FORMAT CHECK FAILED \033[0m"
+          echo -e "\033[31m FORMAT CHECK FAILED \033[0m" && \
+          exit 1
   lint:
     name: ESLint check
     runs-on: ubuntu-latest
@@ -30,7 +31,8 @@ jobs:
           npm ci && \
           npm run lint && \
           echo -e "\033[32m LINT PASSED \033[0m" || \
-          echo -e "\033[31m LINT FAILED \033[0m"
+          echo -e "\033[31m LINT FAILED \033[0m" && \
+          exit 1
 
   windows_test:
     needs: [format, lint]
@@ -41,7 +43,7 @@ jobs:
         uses: actions/checkout@master
       - name: NPM script test
         # Thanks Windows, thanks Microsoft, thanks powershell and cmd
-        run: npm ci && npm run test && echo WINDOWS PASSED || echo WINDOWS FAILED
+        run: npm ci && npm run test && echo WINDOWS PASSED || echo WINDOWS FAILED && exit 1
 
   linux_test:
     needs: [format, lint]
@@ -55,7 +57,8 @@ jobs:
           npm ci && \
           npm run test && \
           echo -e "\033[32m WINDOWS PASSED \033[0m" || \
-          echo -e "\033[31m WINDOWS FAILED \033[0m"
+          echo -e "\033[31m WINDOWS FAILED \033[0m" && \
+          exit 1
 
   darwin_test:
     needs: [format, lint]
@@ -69,4 +72,5 @@ jobs:
           npm ci && \
           npm run test && \
           echo -e "\033[32m WINDOWS PASSED \033[0m" || \
-          echo -e "\033[31m WINDOWS FAILED \033[0m"
+          echo -e "\033[31m WINDOWS FAILED \033[0m" && \
+          exit 1
